#' Simulate survival response based on Cox PH model
#' 
#' Simulate survival response based on Cox PH model that follows either
#' exponential, Weibull, or Gompertz distribution. Linear predictor for
#' the Cox model is given by \eqn{covariate * logHR}
#' 
#' @param n sample size
#' @param logHR coefficients for linear predictor of Cox model
#' @param A matrix of auxiliary covariates for linear predictor of Cox model
#' @param dist desired outcome distribution; choices include "Exponential," (default) "Weibull," or "Gompertz"
#' @param lambda scale parameter for Exponential, Weibull, and Gompertz distributions. Must be positive. Default is \code{1}
#' @param nu shape parameter for Weibull distributions. Must be positive. Default is \code{NULL}
#' @param alpha shape parameter for Gompertz distribution. Default is \code{NULL}
#' 
#' @return a response vector of length \code{n} generated by the specified Cox model
#' 
#' @export
cox_simulation = function(n, logHR, A, dist = "Exponential", 
                          lambda = 1, nu = NULL, alpha = NULL) {
  # test for bad input
  if (n %% 1 != 0 | n < 1) stop("n must be positive integer")
  if (!is.matrix(A)) stop("A must be a matrix of covariates")
  if (length(logHR) != ncol(A)) stop("length(logHR) not equal to ncol(A)")
  if (!(dist %in% c("Exponential", "Weibull", "Gompertz"))) stop("argument dist must be one of: Exponential, Weibull, or Gompertz")
  if (lambda <= 0) stop("lambda must be positive")
  
  # Generate n iid unif(0, 1) random variable
  U = runif(n = n, min = 0, max = 1)
  # Calculate H_0(T) according to Bender (2005)
  H_0.T = -log(U)*exp(-covariate %*% logHR)
  
  # Return simulated response based on distribution character provided
  if (dist == "Exponential") { return(H_0.T/lambda) }
  else if (dist == "Weibull") { return((H_0.T/lambda)^{1/nu}) }
  else if (dist == "Gompertz") { return(log(1 + alpha*t/lambda)/alpha) }
  else { stop("Invalid distribution") }
}