#' Simulate survival response based on Cox PH model
#' 
#' Simulate survival response based on Cox PH model that follows either
#' exponential, Weibull, or Gompertz distribution
#' 
#' @param n sample size
#' @param logHR coefficients for linear predictor of Cox model
#' @param covariate covaraites for linear predictor of Cox model
#' @param dist desired outcome distribution; choices include "Exponential," (default) "Weibull," or "Gompertz"
#' @param lambda simulation parameter for Exponential, Weibull, and Gompertz distributions
#' @param nu simulation parameter for Weibull distributions
#' @param alpha simulation parameter for Gompertz distribution
#' 
#' @return a response vector of length n generated by the specified Cox model
#' 
#' @export
cox.simulation = function(n, logHR, covariate, dist = "Exponential", 
                          lambda = 1, nu = NULL, alpha = NULL) {
  # Generate n iid unif(0, 1) random variable
  U = runif(n = n, min = 0, max = 1)
  # Calculate H_0(T) according to Bender (2005)
  H_0.T = -log(U)*exp(-covariate %*% logHR)
  
  # Return simulated response based on distribution character provided
  if (dist == "Exponential") { return(H_0.T/lambda) }
  else if (dist == "Weibull") { return((H_0.T/lambda)^{1/nu}) }
  else if (dist == "Gompertz") { return(log(1 + alpha*t/lambda)/alpha) }
  else { print("Invalid distribution") }
}