#' Fit a linear model to a list of imputed datasets
#'
#' Takes a list of imputed datasets, as generated by \code{condl_mean_impute_bootstrap()},
#' and returns a list which summarizes estimation of the \code{p} regression coefficients
#' 
#' @param imputed_list A list with dataframe elements that have been completed via conditional mean imputation, such as by \code{condl_mean_impute_bootstrap()}. 
#' @param formula A formula object used to fit a linear model to each dataframe in \code{imputed_list}
#' 
#' @return A list with the following two elements:
#' \item{Coef}{A vector of the \code{p} average coefficient estimates obtained from fitting \code{formula} to each dataframe in \code{imputed_list}}
#' \item{SE}{A vector of the \code{p} average standard error estimates obtained from fitting \code{formula} to each dataframe in \code{imputed_list}}
#' 
#' @export
fit_lm_to_imputed_list = function(imputed_list, formula) {
  # determine number of bootstrap samples
  M = length(imputed_list)
  
  # get list of length M, with each entry a vector of coefficient and SE estimates
  estimates_list <- lapply(X = imputed_list, 
                           FUN = function(x) {
                             model <- lm(formula = formula, data = x)
                             estimates <- c(model$coefficients, sqrt(diag(vcov(model))))
                           })
  
  # capture number of parameters
  p <- length(estimates_list[[1]])/2

  # collapse list of parameter estimates into M x p matrix
  estimates_matrix <- matrix(0, nrow = M, ncol = p)
  SE_matrix <- matrix(0, nrow = M, ncol = p)
  for (i in 1:M) { 
    estimates_matrix[i, ] <- estimates_list[[i]][1:p]
    SE_matrix[i, ] <- estimates_list[[i]][-(1:p)]
  }
  # name columns
  dimnames(estimates_matrix)[[2]] <- dimnames(SE_matrix)[[2]] <- names(estimates_list[[1]])[1:p]
  
  # return column means
  list(Coef = colMeans(estimates_matrix), 
       SE = colMeans(SE_matrix))
}